version: '3.8'

services:
  app:
    image: faridraouf/currency-exchange-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
